kind: equipment_template
schema_version: '3.0'
slot: light_cone
id: dance_dance_dance
name: Dance! Dance! Dance!
cn_name: 舞！舞！舞！
source_file: light_cone_dance_dance_dance_template_v1_6.yaml
equip_requirement: {}
base_stats: {}
superimposition_effects: {}
stack_model: {}
status_effects: {}
triggers: []
raw_user_case: {}
