"""Phase 2-3: 结算系统 — 与引擎状态变更同源的结算记录。"""

from hsr_engine.kernel import (
    KERNEL_FULL_SCENE_SNAPSHOT_ENCODING,
    KERNEL_TRANSITION_ENCODING,
    ActionRequest,
    ActionTransition,
    RNGEvent,
    SourceRef,
    StateChange,
    TargetResolution,
)

from .records import (
    DamageRecord,
    ShieldRecord,
    HPRecord,
    EnergyRecord,
    SPRecord,
    StatusRecord,
    AVRecord,
    TurnRecord,
    MechanicRecord,
    TargetRecord,
    BreakRecord,
    ToughnessRecord,
    DotRecord,
    SuperBreakRecord,
    ENERGY_SOURCE_ACTION,
    ENERGY_SOURCE_HIT_TAKEN,
    ENERGY_SOURCE_KILL,
    ENERGY_SOURCE_COST,
    ENERGY_SOURCE_EFFECT,
    AV_REGULAR_TURN,
    AV_ADVANCE,
    AV_DELAY,
    AV_TIMELINE_TICK,
    BREAK_EVENT,
    TOUGHNESS_REDUCTION,
    DOT_TICK,
    DOT_SOURCE_BREAK,
    DOT_SOURCE_STATUS,
)
from .collector import SettlementCollector

__all__ = [
    "DamageRecord",
    "ShieldRecord",
    "HPRecord",
    "EnergyRecord",
    "SPRecord",
    "StatusRecord",
    "AVRecord",
    "TurnRecord",
    "MechanicRecord",
    "TargetRecord",
    "BreakRecord",
    "ToughnessRecord",
    "DotRecord",
    "SuperBreakRecord",
    "SettlementCollector",
    "KERNEL_TRANSITION_ENCODING",
    "KERNEL_FULL_SCENE_SNAPSHOT_ENCODING",
    "ActionRequest",
    "ActionTransition",
    "RNGEvent",
    "SourceRef",
    "StateChange",
    "TargetResolution",
    "ENERGY_SOURCE_ACTION",
    "ENERGY_SOURCE_HIT_TAKEN",
    "ENERGY_SOURCE_KILL",
    "ENERGY_SOURCE_COST",
    "ENERGY_SOURCE_EFFECT",
    "AV_REGULAR_TURN",
    "AV_ADVANCE",
    "AV_DELAY",
    "AV_TIMELINE_TICK",
    "BREAK_EVENT",
    "TOUGHNESS_REDUCTION",
    "DOT_TICK",
    "DOT_SOURCE_BREAK",
    "DOT_SOURCE_STATUS",
]
